services:
  auctioneer:
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/auctioneer:v0.2.5
    ports:
      - "1252:9000"
    restart: yes
    networks:
      - poptape
networks:
  poptape:
    external: true